import type { Exercise, MuscleGroup } from "./fitness-types";

// Initial exercise library. To give an exercise a real image, drop the file
// under `public/exercises/<muscle-group>/<imageKey>.png` and set `imagePath`
// on the exercise (see public/exercises/README.md). Exercises without an
// `imagePath` render the gradient placeholder derived from `muscleGroup`.
export const SEED_EXERCISES: Exercise[] = [
  {
    id: "lat-pulldown",
    nameEn: "Lat Pulldown",
    nameHe: "פולי עליון",
    muscleGroup: "back",
    secondaryMuscles: ["biceps"],
    equipment: "cable",
    difficulty: "beginner",
    imageKey: "lat-pulldown",
    imagePath: "/exercises/back/lat-pulldown.webp",
    instructions: [
      "אחזו במוט באחיזה רחבה מעט מרוחב הכתפיים.",
      "משכו את המוט אל בית החזה תוך כיווץ השכמות.",
      "החזירו בשליטה למצב התחלתי עם מתיחה מלאה.",
    ],
    notes: "שמרו על חזה פתוח והימנעו מתנופה.",
  },
  {
    id: "pull-ups",
    nameEn: "Pull Ups",
    nameHe: "מתח",
    muscleGroup: "back",
    secondaryMuscles: ["biceps", "core"],
    equipment: "bodyweight",
    difficulty: "advanced",
    imageKey: "pull-ups",
    imagePath: "/exercises/back/pull-ups.webp",
    instructions: [
      "תלו על המוט באחיזה רחבה מרוחב הכתפיים.",
      "משכו את הגוף כלפי מעלה עד שהסנטר מעל המוט.",
      "רדו בשליטה ליישור מלא של המרפקים.",
    ],
  },
  {
    id: "bent-over-row",
    nameEn: "Bent Over Row",
    nameHe: "חתירה בהרכנה",
    muscleGroup: "back",
    secondaryMuscles: ["biceps", "core"],
    equipment: "barbell",
    difficulty: "intermediate",
    imageKey: "bent-over-row",
    imagePath: "/exercises/back/bent-over-row.webp",
    instructions: [
      "הרכינו את פלג הגוף העליון כ-45 מעלות עם גב ישר.",
      "משכו את המוט אל הבטן התחתונה.",
      "הורידו בשליטה ושמרו על ליבה אקטיבית.",
    ],
  },
  {
    id: "landmine-row",
    nameEn: "Landmine Row",
    nameHe: "חתירת לנדמיין",
    muscleGroup: "back",
    secondaryMuscles: ["biceps"],
    equipment: "barbell",
    difficulty: "intermediate",
    imageKey: "landmine-row",
    imagePath: "/exercises/back/landmine-row.webp",
    instructions: [
      "הציבו את קצה המוט בעוגן לנדמיין.",
      "אחזו בקצה הפנוי ומשכו אל החזה.",
      "שמרו על גב ניטרלי לאורך התנועה.",
    ],
  },
  {
    id: "romanian-deadlift",
    nameEn: "Romanian Deadlift",
    nameHe: "דדליפט רומני",
    muscleGroup: "glutes",
    secondaryMuscles: ["legs", "back"],
    equipment: "barbell",
    difficulty: "intermediate",
    imageKey: "romanian-deadlift",
    imagePath: "/exercises/glutes/romanian-deadlift.webp",
    instructions: [
      "החזיקו את המוט קרוב לרגליים עם ברכיים מעט כפופות.",
      "דחפו את הירכיים אחורה תוך שמירה על גב ישר.",
      "הרגישו מתיחה בירך האחורית וחזרו למעלה.",
    ],
    notes: "התנועה מגיעה מהירכיים ולא מהגב התחתון.",
  },
  {
    id: "rack-pull",
    nameEn: "Rack Pull",
    nameHe: "ראק פול",
    muscleGroup: "back",
    secondaryMuscles: ["glutes", "legs"],
    equipment: "barbell",
    difficulty: "advanced",
    imageKey: "rack-pull",
    imagePath: "/exercises/back/rack-pull.webp",
    instructions: [
      "הציבו את המוט על נקודות בטיחות מתחת לגובה הברך.",
      "אחזו במוט ומשכו עד יישור מלא של הירכיים.",
      "הורידו בשליטה אל נקודות הבטיחות.",
    ],
  },
  {
    id: "chin-up",
    nameEn: "Chin Up",
    nameHe: "מתח באחיזה הפוכה",
    muscleGroup: "back",
    secondaryMuscles: ["biceps"],
    equipment: "bodyweight",
    difficulty: "intermediate",
    imageKey: "chin-up",
    imagePath: "/exercises/back/chin-up.webp",
    instructions: [
      "תלו על המוט באחיזה הפוכה ברוחב הכתפיים.",
      "משכו את הגוף כלפי מעלה עד שהסנטר מעל המוט.",
      "רדו בשליטה ליישור מלא של המרפקים.",
    ],
    notes: "האחיזה ההפוכה מערבת את היד הקדמית יותר ממתח רגיל.",
  },
  {
    id: "neutral-grip-pull-up",
    nameEn: "Neutral Grip Pull Up",
    nameHe: "מתח באחיזה ניטרלית",
    muscleGroup: "back",
    secondaryMuscles: ["biceps", "core"],
    equipment: "bodyweight",
    difficulty: "advanced",
    imageKey: "neutral-grip-pull-up",
    imagePath: "/exercises/back/neutral-grip-pull-up.webp",
    instructions: [
      "תלו על ידיות מקבילות כשכפות הידיים פונות זו לזו.",
      "משכו את הגוף כלפי מעלה עד שהסנטר בגובה הידיות.",
      "רדו בשליטה ליישור מלא של המרפקים.",
    ],
    notes: "אחיזה נוחה יותר לכתפיים ולמרפקים.",
  },
  {
    id: "seated-cable-row",
    nameEn: "Seated Cable Row",
    nameHe: "חתירה בישיבה בפולי",
    muscleGroup: "back",
    secondaryMuscles: ["biceps"],
    equipment: "cable",
    difficulty: "beginner",
    imageKey: "seated-cable-row",
    imagePath: "/exercises/back/seated-cable-row.webp",
    instructions: [
      "שבו מול הפולי עם ברכיים מעט כפופות וגב ישר.",
      "משכו את הידית אל הבטן תוך כיווץ השכמות.",
      "החזירו בשליטה עד מתיחה מלאה של הגב.",
    ],
  },
  {
    id: "single-arm-dumbbell-row",
    nameEn: "Single Arm Dumbbell Row",
    nameHe: "חתירת משקולת ביד אחת",
    muscleGroup: "back",
    secondaryMuscles: ["biceps", "core"],
    equipment: "dumbbell",
    difficulty: "beginner",
    imageKey: "single-arm-dumbbell-row",
    imagePath: "/exercises/back/single-arm-dumbbell-row.webp",
    instructions: [
      "הניחו יד וברך על ספסל ושמרו על גב ישר.",
      "משכו את המשקולת אל המותן תוך כיווץ השכמה.",
      "הורידו בשליטה למתיחה מלאה.",
    ],
  },
  {
    id: "face-pull",
    nameEn: "Face Pull",
    nameHe: "פייס פול",
    muscleGroup: "back",
    secondaryMuscles: ["shoulders"],
    equipment: "cable",
    difficulty: "beginner",
    imageKey: "face-pull",
    imagePath: "/exercises/back/face-pull.webp",
    instructions: [
      "כוונו את הפולי לגובה הפנים עם חבל כפול.",
      "משכו את החבל אל הפנים תוך פתיחת המרפקים לצדדים.",
      "החזירו בשליטה תוך שמירה על כתפיים משוחררות.",
    ],
    notes: "תרגיל מצוין לחיזוק הכתף האחורית ויציבה.",
  },
  {
    id: "close-grip-lat-pulldown",
    nameEn: "Close Grip Lat Pulldown",
    nameHe: "פולי עליון באחיזה צרה",
    muscleGroup: "back",
    secondaryMuscles: ["biceps"],
    equipment: "cable",
    difficulty: "beginner",
    imageKey: "close-grip-lat-pulldown",
    imagePath: "/exercises/back/close-grip-lat-pulldown.webp",
    instructions: [
      "אחזו בידית צרה כשכפות הידיים קרובות זו לזו.",
      "משכו את הידית אל בית החזה תוך כיווץ השכמות.",
      "החזירו בשליטה למתיחה מלאה.",
    ],
  },
  {
    id: "chest-supported-row",
    nameEn: "Chest Supported Row",
    nameHe: "חתירה בתמיכת חזה",
    muscleGroup: "back",
    secondaryMuscles: ["biceps"],
    equipment: "machine",
    difficulty: "beginner",
    imageKey: "chest-supported-row",
    imagePath: "/exercises/back/chest-supported-row.webp",
    instructions: [
      "הצמידו את החזה למשענת ואחזו בידיות.",
      "משכו את הידיות לאחור תוך כיווץ השכמות.",
      "החזירו בשליטה למתיחה מלאה.",
    ],
    notes: "התמיכה מנטרלת את הגב התחתון ומבודדת את שרירי הגב.",
  },
  {
    id: "straight-arm-pulldown",
    nameEn: "Straight Arm Pulldown",
    nameHe: "פולי ישר בידיים ישרות",
    muscleGroup: "back",
    secondaryMuscles: ["triceps"],
    equipment: "cable",
    difficulty: "intermediate",
    imageKey: "straight-arm-pulldown",
    imagePath: "/exercises/back/straight-arm-pulldown.webp",
    instructions: [
      "עמדו מול פולי עליון ואחזו במוט בידיים ישרות.",
      "הורידו את המוט אל הירכיים בקשת רחבה ללא כיפוף מרפקים.",
      "החזירו בשליטה למעלה עד מתיחה מלאה של הגב.",
    ],
  },
  {
    id: "single-arm-lat-pulldown",
    nameEn: "Single Arm Lat Pulldown",
    nameHe: "פולי עליון ביד אחת",
    muscleGroup: "back",
    secondaryMuscles: ["biceps"],
    equipment: "cable",
    difficulty: "beginner",
    imageKey: "single-arm-lat-pulldown",
    imagePath: "/exercises/back/single-arm-lat-pulldown.webp",
    instructions: [
      "אחזו בידית פולי עליון ביד אחת.",
      "משכו את הידית אל הכתף תוך כיווץ השכמה.",
      "החזירו בשליטה למתיחה מלאה.",
    ],
  },
  {
    id: "t-bar-row",
    nameEn: "T-Bar Row",
    nameHe: "חתירת טי-בר",
    muscleGroup: "back",
    secondaryMuscles: ["biceps", "core"],
    equipment: "barbell",
    difficulty: "intermediate",
    imageKey: "t-bar-row",
    imagePath: "/exercises/back/t-bar-row.webp",
    instructions: [
      "עמדו מעל המוט בהרכנה עם גב ישר.",
      "משכו את הידית אל בית החזה תוך כיווץ השכמות.",
      "הורידו בשליטה עד מתיחה מלאה.",
    ],
  },
  {
    id: "wide-grip-lat-pulldown",
    nameEn: "Wide Grip Lat Pulldown",
    nameHe: "פולי עליון באחיזה רחבה",
    muscleGroup: "back",
    secondaryMuscles: ["biceps"],
    equipment: "cable",
    difficulty: "beginner",
    imageKey: "wide-grip-lat-pulldown",
    imagePath: "/exercises/back/wide-grip-lat-pulldown.webp",
    instructions: [
      "אחזו במוט באחיזה רחבה משמעותית מרוחב הכתפיים.",
      "משכו את המוט אל בית החזה תוך כיווץ השכמות.",
      "החזירו בשליטה למתיחה מלאה.",
    ],
  },
  {
    id: "reverse-grip-lat-pulldown",
    nameEn: "Reverse Grip Lat Pulldown",
    nameHe: "פולי עליון באחיזה הפוכה",
    muscleGroup: "back",
    secondaryMuscles: ["biceps"],
    equipment: "cable",
    difficulty: "beginner",
    imageKey: "reverse-grip-lat-pulldown",
    imagePath: "/exercises/back/reverse-grip-lat-pulldown.webp",
    instructions: [
      "אחזו במוט באחיזה הפוכה ברוחב הכתפיים.",
      "משכו את המוט אל בית החזה תוך כיווץ השכמות.",
      "החזירו בשליטה למתיחה מלאה.",
    ],
  },
  {
    id: "wide-grip-seated-row",
    nameEn: "Wide Grip Seated Row",
    nameHe: "חתירה בישיבה באחיזה רחבה",
    muscleGroup: "back",
    secondaryMuscles: ["biceps", "shoulders"],
    equipment: "cable",
    difficulty: "beginner",
    imageKey: "wide-grip-seated-row",
    imagePath: "/exercises/back/wide-grip-seated-row.webp",
    instructions: [
      "שבו מול הפולי ואחזו במוט רחב בשתי הידיים.",
      "משכו את המוט אל בית החזה עם מרפקים גבוהים.",
      "החזירו בשליטה למתיחה מלאה.",
    ],
  },
  {
    id: "reverse-grip-barbell-row",
    nameEn: "Reverse Grip Barbell Row",
    nameHe: "חתירת מוט באחיזה הפוכה",
    muscleGroup: "back",
    secondaryMuscles: ["biceps", "core"],
    equipment: "barbell",
    difficulty: "intermediate",
    imageKey: "reverse-grip-barbell-row",
    imagePath: "/exercises/back/reverse-grip-barbell-row.webp",
    instructions: [
      "הרכינו את פלג הגוף העליון עם גב ישר ואחיזה הפוכה.",
      "משכו את המוט אל הבטן התחתונה.",
      "הורידו בשליטה ושמרו על ליבה אקטיבית.",
    ],
  },
  {
    id: "bench-press",
    nameEn: "Bench Press",
    nameHe: "לחיצת חזה",
    muscleGroup: "chest",
    secondaryMuscles: ["triceps", "shoulders"],
    equipment: "barbell",
    difficulty: "intermediate",
    imageKey: "bench-press",
    imagePath: "/exercises/chest/bench-press.webp",
    instructions: [
      "שכבו על הספסל עם אחיזה מעט רחבה מהכתפיים.",
      "הורידו את המוט אל אמצע החזה בשליטה.",
      "דחפו כלפי מעלה עד יישור המרפקים.",
    ],
  },
  {
    id: "incline-bench-press",
    nameEn: "Incline Bench Press",
    nameHe: "לחיצת חזה בשיפוע עולה",
    muscleGroup: "chest",
    secondaryMuscles: ["shoulders", "triceps"],
    equipment: "barbell",
    difficulty: "intermediate",
    imageKey: "incline-bench-press",
    imagePath: "/exercises/chest/incline-bench-press.webp",
    instructions: [
      "שכבו על ספסל בשיפוע של 30-45 מעלות.",
      "הורידו את המוט אל החזה העליון בשליטה.",
      "דחפו כלפי מעלה עד יישור המרפקים.",
    ],
    notes: "השיפוע מעביר דגש לחלק העליון של החזה.",
  },
  {
    id: "decline-bench-press",
    nameEn: "Decline Bench Press",
    nameHe: "לחיצת חזה בשיפוע יורד",
    muscleGroup: "chest",
    secondaryMuscles: ["triceps"],
    equipment: "barbell",
    difficulty: "intermediate",
    imageKey: "decline-bench-press",
    imagePath: "/exercises/chest/decline-bench-press.webp",
    instructions: [
      "שכבו על ספסל בשיפוע יורד עם רגליים מקובעות.",
      "הורידו את המוט אל החזה התחתון בשליטה.",
      "דחפו כלפי מעלה עד יישור המרפקים.",
    ],
  },
  {
    id: "dumbbell-bench-press",
    nameEn: "Dumbbell Bench Press",
    nameHe: "לחיצת חזה עם משקולות",
    muscleGroup: "chest",
    secondaryMuscles: ["triceps", "shoulders"],
    equipment: "dumbbell",
    difficulty: "beginner",
    imageKey: "dumbbell-bench-press",
    imagePath: "/exercises/chest/dumbbell-bench-press.webp",
    instructions: [
      "שכבו על ספסל עם משקולת בכל יד בגובה החזה.",
      "דחפו את המשקולות כלפי מעלה עד יישור המרפקים.",
      "הורידו בשליטה לגובה החזה.",
    ],
    notes: "מאפשר טווח תנועה גדול יותר מלחיצה עם מוט.",
  },
  {
    id: "incline-dumbbell-press",
    nameEn: "Incline Dumbbell Press",
    nameHe: "לחיצת משקולות בשיפוע עולה",
    muscleGroup: "chest",
    secondaryMuscles: ["shoulders", "triceps"],
    equipment: "dumbbell",
    difficulty: "intermediate",
    imageKey: "incline-dumbbell-press",
    imagePath: "/exercises/chest/incline-dumbbell-press.webp",
    instructions: [
      "שכבו על ספסל בשיפוע עולה עם משקולת בכל יד.",
      "דחפו את המשקולות כלפי מעלה מעל החזה העליון.",
      "הורידו בשליטה לגובה הכתפיים.",
    ],
  },
  {
    id: "chest-fly",
    nameEn: "Chest Fly",
    nameHe: "פרפר עם משקולות",
    muscleGroup: "chest",
    secondaryMuscles: ["shoulders"],
    equipment: "dumbbell",
    difficulty: "beginner",
    imageKey: "chest-fly",
    imagePath: "/exercises/chest/chest-fly.webp",
    instructions: [
      "שכבו על ספסל עם משקולות מעל החזה וכפות ידיים פונות זו לזו.",
      "פתחו את הידיים לצדדים בקשת רחבה עם מרפקים מעט כפופים.",
      "החזירו את המשקולות מעלה באותה קשת תוך כיווץ החזה.",
    ],
  },
  {
    id: "incline-dumbbell-fly",
    nameEn: "Incline Dumbbell Fly",
    nameHe: "פרפר בשיפוע עולה",
    muscleGroup: "chest",
    secondaryMuscles: ["shoulders"],
    equipment: "dumbbell",
    difficulty: "intermediate",
    imageKey: "incline-dumbbell-fly",
    imagePath: "/exercises/chest/incline-dumbbell-fly.webp",
    instructions: [
      "שכבו על ספסל בשיפוע עולה עם משקולות מעל החזה.",
      "פתחו את הידיים לצדדים בקשת רחבה עם מרפקים מעט כפופים.",
      "החזירו מעלה תוך כיווץ החזה העליון.",
    ],
  },
  {
    id: "cable-chest-fly",
    nameEn: "Cable Chest Fly",
    nameHe: "פרפר בפולי",
    muscleGroup: "chest",
    secondaryMuscles: ["shoulders"],
    equipment: "cable",
    difficulty: "beginner",
    imageKey: "cable-chest-fly",
    imagePath: "/exercises/chest/cable-chest-fly.webp",
    instructions: [
      "עמדו בין שני פולים בגובה החזה עם ידית בכל יד.",
      "קרבו את הידיים זו לזו לפנים בקשת רחבה.",
      "החזירו בשליטה עד מתיחה נעימה בחזה.",
    ],
    notes: "הפולי שומר על מתח רציף לאורך כל התנועה.",
  },
  {
    id: "low-cable-fly",
    nameEn: "Low Cable Fly",
    nameHe: "פרפר בפולי תחתון",
    muscleGroup: "chest",
    secondaryMuscles: ["shoulders"],
    equipment: "cable",
    difficulty: "intermediate",
    imageKey: "low-cable-fly",
    imagePath: "/exercises/chest/low-cable-fly.webp",
    instructions: [
      "כוונו את הפולים לעמדה נמוכה ואחזו בידיות.",
      "הרימו את הידיים מלמטה כלפי מעלה ופנימה אל מול החזה.",
      "החזירו בשליטה למצב התחלתי.",
    ],
    notes: "דגש על החלק העליון של החזה.",
  },
  {
    id: "high-cable-fly",
    nameEn: "High Cable Fly",
    nameHe: "פרפר בפולי עליון",
    muscleGroup: "chest",
    secondaryMuscles: ["shoulders"],
    equipment: "cable",
    difficulty: "intermediate",
    imageKey: "high-cable-fly",
    imagePath: "/exercises/chest/high-cable-fly.webp",
    instructions: [
      "כוונו את הפולים לעמדה גבוהה ואחזו בידיות.",
      "משכו את הידיים מלמעלה כלפי מטה ופנימה אל מול הבטן.",
      "החזירו בשליטה למצב התחלתי.",
    ],
    notes: "דגש על החלק התחתון של החזה.",
  },
  {
    id: "machine-chest-press",
    nameEn: "Machine Chest Press",
    nameHe: "לחיצת חזה במכונה",
    muscleGroup: "chest",
    secondaryMuscles: ["triceps"],
    equipment: "machine",
    difficulty: "beginner",
    imageKey: "machine-chest-press",
    imagePath: "/exercises/chest/machine-chest-press.webp",
    instructions: [
      "שבו במכונה עם הידיות בגובה החזה.",
      "דחפו את הידיות קדימה עד יישור המרפקים.",
      "החזירו בשליטה למצב התחלתי.",
    ],
    notes: "מסלול מונחה — מתאים מאוד למתחילים.",
  },
  {
    id: "pec-deck-fly",
    nameEn: "Pec Deck Fly",
    nameHe: "פרפר במכונה",
    muscleGroup: "chest",
    secondaryMuscles: ["shoulders"],
    equipment: "machine",
    difficulty: "beginner",
    imageKey: "pec-deck-fly",
    imagePath: "/exercises/chest/pec-deck-fly.webp",
    instructions: [
      "שבו במכונה עם גב צמוד למשענת וידיים על הידיות.",
      "קרבו את הידיות זו לזו תוך כיווץ החזה.",
      "החזירו בשליטה עד מתיחה נעימה.",
    ],
  },
  {
    id: "smith-machine-bench-press",
    nameEn: "Smith Machine Bench Press",
    nameHe: "לחיצת חזה בסמית' משין",
    muscleGroup: "chest",
    secondaryMuscles: ["triceps", "shoulders"],
    equipment: "machine",
    difficulty: "beginner",
    imageKey: "smith-machine-bench-press",
    imagePath: "/exercises/chest/smith-machine-bench-press.webp",
    instructions: [
      "שכבו על ספסל מתחת למוט הסמית' משין.",
      "הורידו את המוט אל אמצע החזה בשליטה.",
      "דחפו כלפי מעלה עד יישור המרפקים.",
    ],
    notes: "המסלול הקבוע מאפשר עבודה בטוחה ללא שומר.",
  },
  {
    id: "push-up",
    nameEn: "Push Up",
    nameHe: "שכיבות סמיכה",
    muscleGroup: "chest",
    secondaryMuscles: ["triceps", "core"],
    equipment: "bodyweight",
    difficulty: "beginner",
    imageKey: "push-up",
    imagePath: "/exercises/chest/push-up.webp",
    instructions: [
      "התמקמו בפלאנק עם ידיים מעט רחבות מהכתפיים.",
      "הורידו את הגוף עד שהחזה כמעט נוגע ברצפה.",
      "דחפו חזרה למעלה תוך שמירה על גוף ישר.",
    ],
  },
  {
    id: "incline-push-up",
    nameEn: "Incline Push Up",
    nameHe: "שכיבות סמיכה בשיפוע עולה",
    muscleGroup: "chest",
    secondaryMuscles: ["triceps", "core"],
    equipment: "bodyweight",
    difficulty: "beginner",
    imageKey: "incline-push-up",
    imagePath: "/exercises/chest/incline-push-up.webp",
    instructions: [
      "הניחו את הידיים על משטח מוגבה כמו ספסל.",
      "הורידו את החזה אל המשטח בשליטה.",
      "דחפו חזרה למעלה תוך שמירה על גוף ישר.",
    ],
    notes: "גרסה קלה יותר — מתאימה לבניית בסיס.",
  },
  {
    id: "decline-push-up",
    nameEn: "Decline Push Up",
    nameHe: "שכיבות סמיכה בשיפוע יורד",
    muscleGroup: "chest",
    secondaryMuscles: ["shoulders", "triceps"],
    equipment: "bodyweight",
    difficulty: "intermediate",
    imageKey: "decline-push-up",
    imagePath: "/exercises/chest/decline-push-up.webp",
    instructions: [
      "הניחו את כפות הרגליים על משטח מוגבה וידיים על הרצפה.",
      "הורידו את החזה אל הרצפה בשליטה.",
      "דחפו חזרה למעלה תוך שמירה על גוף ישר.",
    ],
    notes: "ההגבהה מעבירה דגש לחזה העליון ולכתפיים.",
  },
  {
    id: "dips-chest-focus",
    nameEn: "Dips (Chest Focus)",
    nameHe: "מקבילים בדגש חזה",
    muscleGroup: "chest",
    secondaryMuscles: ["triceps", "shoulders"],
    equipment: "bodyweight",
    difficulty: "advanced",
    imageKey: "dips-chest-focus",
    imagePath: "/exercises/chest/dips-chest-focus.webp",
    instructions: [
      "אחזו במקבילים והרכינו את פלג הגוף העליון מעט קדימה.",
      "רדו בשליטה עד שהכתפיים בגובה המרפקים.",
      "דחפו חזרה למעלה תוך שמירה על ההרכנה קדימה.",
    ],
    notes: "ההרכנה קדימה מעבירה את הדגש מהיד האחורית לחזה.",
  },
  {
    id: "dumbbell-pullover",
    nameEn: "Dumbbell Pullover",
    nameHe: "פולאובר עם משקולת",
    muscleGroup: "chest",
    secondaryMuscles: ["back", "triceps"],
    equipment: "dumbbell",
    difficulty: "intermediate",
    imageKey: "dumbbell-pullover",
    imagePath: "/exercises/chest/dumbbell-pullover.webp",
    instructions: [
      "שכבו על ספסל ואחזו משקולת אחת בשתי הידיים מעל החזה.",
      "הורידו את המשקולת לאחור מעבר לראש בקשת רחבה.",
      "החזירו מעל החזה תוך כיווץ החזה והגב.",
    ],
  },
  {
    id: "landmine-chest-press",
    nameEn: "Landmine Chest Press",
    nameHe: "לחיצת חזה בלנדמיין",
    muscleGroup: "chest",
    secondaryMuscles: ["shoulders", "triceps"],
    equipment: "barbell",
    difficulty: "intermediate",
    imageKey: "landmine-chest-press",
    imagePath: "/exercises/chest/landmine-chest-press.webp",
    instructions: [
      "הציבו את קצה המוט בעוגן לנדמיין ואחזו בקצה הפנוי בגובה החזה.",
      "דחפו את המוט קדימה ומעלה עד יישור הזרוע.",
      "החזירו בשליטה לגובה החזה.",
    ],
  },
  {
    id: "svend-press",
    nameEn: "Svend Press",
    nameHe: "לחיצת סבנד",
    muscleGroup: "chest",
    secondaryMuscles: ["shoulders", "triceps"],
    equipment: "dumbbell",
    difficulty: "beginner",
    imageKey: "svend-press",
    imagePath: "/exercises/chest/svend-press.webp",
    instructions: [
      "לחצו משקל קל בין שתי כפות הידיים בגובה החזה.",
      "דחפו את המשקל קדימה תוך לחיצה מתמשכת של הידיים זו אל זו.",
      "החזירו בשליטה אל החזה.",
    ],
    notes: "מתבצע לרוב עם צלחת משקל; הציוד מסומן כמשקולת לבדיקה עתידית.",
  },
  {
    id: "shoulder-press",
    nameEn: "Shoulder Press",
    nameHe: "לחיצת כתפיים",
    muscleGroup: "shoulders",
    secondaryMuscles: ["triceps"],
    equipment: "dumbbell",
    difficulty: "beginner",
    imageKey: "shoulder-press",
    instructions: [
      "אחזו משקולות בגובה הכתפיים.",
      "דחפו כלפי מעלה עד יישור הזרועות.",
      "הורידו בשליטה לגובה הכתפיים.",
    ],
  },
  {
    id: "squat",
    nameEn: "Squat",
    nameHe: "סקוואט",
    muscleGroup: "legs",
    secondaryMuscles: ["glutes", "core"],
    equipment: "barbell",
    difficulty: "intermediate",
    imageKey: "squat",
    instructions: [
      "הניחו את המוט על הטרפזים העליונים.",
      "רדו תוך דחיפת ירכיים אחורה עד עומק מקביל.",
      "דחפו דרך העקבים בחזרה למעלה.",
    ],
    notes: "שמרו על ברכיים בכיוון האצבעות.",
  },
  {
    id: "biceps-curl",
    nameEn: "Biceps Curl",
    nameHe: "כפיפת מרפקים",
    muscleGroup: "biceps",
    secondaryMuscles: [],
    equipment: "dumbbell",
    difficulty: "beginner",
    imageKey: "biceps-curl",
    instructions: [
      "עמדו עם משקולות לצד הגוף.",
      "כפפו את המרפקים והרימו את המשקולות.",
      "הורידו בשליטה מלאה.",
    ],
  },
  {
    id: "triceps-pushdown",
    nameEn: "Triceps Pushdown",
    nameHe: "פשיטת מרפקים בפולי",
    muscleGroup: "triceps",
    secondaryMuscles: [],
    equipment: "cable",
    difficulty: "beginner",
    imageKey: "triceps-pushdown",
    instructions: [
      "אחזו בידית הפולי בגובה החזה.",
      "פשטו את המרפקים כלפי מטה עד יישור מלא.",
      "החזירו בשליטה תוך שמירה על מרפקים צמודים.",
    ],
  },
  {
    id: "plank",
    nameEn: "Plank",
    nameHe: "פלאנק",
    muscleGroup: "core",
    secondaryMuscles: ["shoulders"],
    equipment: "bodyweight",
    difficulty: "beginner",
    imageKey: "plank",
    instructions: [
      "התמקמו על האמות וקצות האצבעות.",
      "שמרו על קו ישר מהראש ועד העקבים.",
      "כווצו ליבה ועכוז והחזיקו את הזמן הנדרש.",
    ],
  },
];

export const MUSCLE_GROUP_LABELS: Record<MuscleGroup, string> = {
  back: "גב",
  chest: "חזה",
  shoulders: "כתפיים",
  legs: "רגליים",
  glutes: "עכוז",
  biceps: "יד קדמית",
  triceps: "יד אחורית",
  core: "ליבה",
};

export const EQUIPMENT_LABELS: Record<Exercise["equipment"], string> = {
  barbell: "מוט",
  dumbbell: "משקולות",
  machine: "מכונה",
  cable: "פולי",
  bodyweight: "משקל גוף",
  kettlebell: "קטלבל",
};

export const DIFFICULTY_LABELS: Record<Exercise["difficulty"], string> = {
  beginner: "מתחיל",
  intermediate: "מתקדם",
  advanced: "מומחה",
};

export function getExerciseById(id: string): Exercise | undefined {
  return SEED_EXERCISES.find((exercise) => exercise.id === id);
}

/** Unique primary muscle groups for a list of exercise ids, in order. */
export function muscleGroupsForExercises(exerciseIds: string[]): MuscleGroup[] {
  const groups = new Set<MuscleGroup>();
  for (const id of exerciseIds) {
    const exercise = getExerciseById(id);
    if (exercise) groups.add(exercise.muscleGroup);
  }
  return [...groups];
}
