import type { Exercise, MuscleGroup } from "./fitness-types";

// Initial exercise library. To give an exercise a real image, drop the file
// under `public/exercises/<muscle-group>/<imageKey>.png` and set `imagePath`
// on the exercise (see public/exercises/README.md). Exercises without an
// `imagePath` render the gradient placeholder derived from `muscleGroup`.
export const SEED_EXERCISES: Exercise[] = [
  {
    id: "lat-pulldown",
    nameEn: "Lat Pulldown",
    nameHe: "פולי עליון",
    muscleGroup: "back",
    secondaryMuscles: ["biceps"],
    equipment: "cable",
    difficulty: "beginner",
    imageKey: "lat-pulldown",
    imagePath: "/exercises/back/lat-pulldown.webp",
    instructions: [
      "אחזו במוט באחיזה רחבה מעט מרוחב הכתפיים.",
      "משכו את המוט אל בית החזה תוך כיווץ השכמות.",
      "החזירו בשליטה למצב התחלתי עם מתיחה מלאה.",
    ],
    notes: "שמרו על חזה פתוח והימנעו מתנופה.",
  },
  {
    id: "pull-ups",
    nameEn: "Pull Ups",
    nameHe: "מתח",
    muscleGroup: "back",
    secondaryMuscles: ["biceps", "core"],
    equipment: "bodyweight",
    difficulty: "advanced",
    imageKey: "pull-ups",
    imagePath: "/exercises/back/pull-ups.webp",
    instructions: [
      "תלו על המוט באחיזה רחבה מרוחב הכתפיים.",
      "משכו את הגוף כלפי מעלה עד שהסנטר מעל המוט.",
      "רדו בשליטה ליישור מלא של המרפקים.",
    ],
  },
  {
    id: "bent-over-row",
    nameEn: "Bent Over Row",
    nameHe: "חתירה בהרכנה",
    muscleGroup: "back",
    secondaryMuscles: ["biceps", "core"],
    equipment: "barbell",
    difficulty: "intermediate",
    imageKey: "bent-over-row",
    imagePath: "/exercises/back/bent-over-row.webp",
    instructions: [
      "הרכינו את פלג הגוף העליון כ-45 מעלות עם גב ישר.",
      "משכו את המוט אל הבטן התחתונה.",
      "הורידו בשליטה ושמרו על ליבה אקטיבית.",
    ],
  },
  {
    id: "landmine-row",
    nameEn: "Landmine Row",
    nameHe: "חתירת לנדמיין",
    muscleGroup: "back",
    secondaryMuscles: ["biceps"],
    equipment: "barbell",
    difficulty: "intermediate",
    imageKey: "landmine-row",
    imagePath: "/exercises/back/landmine-row.webp",
    instructions: [
      "הציבו את קצה המוט בעוגן לנדמיין.",
      "אחזו בקצה הפנוי ומשכו אל החזה.",
      "שמרו על גב ניטרלי לאורך התנועה.",
    ],
  },
  {
    id: "romanian-deadlift",
    nameEn: "Romanian Deadlift",
    nameHe: "דדליפט רומני",
    muscleGroup: "glutes",
    secondaryMuscles: ["legs", "back"],
    equipment: "barbell",
    difficulty: "intermediate",
    imageKey: "romanian-deadlift",
    imagePath: "/exercises/glutes/romanian-deadlift.webp",
    instructions: [
      "החזיקו את המוט קרוב לרגליים עם ברכיים מעט כפופות.",
      "דחפו את הירכיים אחורה תוך שמירה על גב ישר.",
      "הרגישו מתיחה בירך האחורית וחזרו למעלה.",
    ],
    notes: "התנועה מגיעה מהירכיים ולא מהגב התחתון.",
  },
  {
    id: "rack-pull",
    nameEn: "Rack Pull",
    nameHe: "ראק פול",
    muscleGroup: "back",
    secondaryMuscles: ["glutes", "legs"],
    equipment: "barbell",
    difficulty: "advanced",
    imageKey: "rack-pull",
    imagePath: "/exercises/back/rack-pull.webp",
    instructions: [
      "הציבו את המוט על נקודות בטיחות מתחת לגובה הברך.",
      "אחזו במוט ומשכו עד יישור מלא של הירכיים.",
      "הורידו בשליטה אל נקודות הבטיחות.",
    ],
  },
  {
    id: "chin-up",
    nameEn: "Chin Up",
    nameHe: "מתח באחיזה הפוכה",
    muscleGroup: "back",
    secondaryMuscles: ["biceps"],
    equipment: "bodyweight",
    difficulty: "intermediate",
    imageKey: "chin-up",
    imagePath: "/exercises/back/chin-up.webp",
    instructions: [
      "תלו על המוט באחיזה הפוכה ברוחב הכתפיים.",
      "משכו את הגוף כלפי מעלה עד שהסנטר מעל המוט.",
      "רדו בשליטה ליישור מלא של המרפקים.",
    ],
    notes: "האחיזה ההפוכה מערבת את היד הקדמית יותר ממתח רגיל.",
  },
  {
    id: "neutral-grip-pull-up",
    nameEn: "Neutral Grip Pull Up",
    nameHe: "מתח באחיזה ניטרלית",
    muscleGroup: "back",
    secondaryMuscles: ["biceps", "core"],
    equipment: "bodyweight",
    difficulty: "advanced",
    imageKey: "neutral-grip-pull-up",
    imagePath: "/exercises/back/neutral-grip-pull-up.webp",
    instructions: [
      "תלו על ידיות מקבילות כשכפות הידיים פונות זו לזו.",
      "משכו את הגוף כלפי מעלה עד שהסנטר בגובה הידיות.",
      "רדו בשליטה ליישור מלא של המרפקים.",
    ],
    notes: "אחיזה נוחה יותר לכתפיים ולמרפקים.",
  },
  {
    id: "seated-cable-row",
    nameEn: "Seated Cable Row",
    nameHe: "חתירה בישיבה בפולי",
    muscleGroup: "back",
    secondaryMuscles: ["biceps"],
    equipment: "cable",
    difficulty: "beginner",
    imageKey: "seated-cable-row",
    imagePath: "/exercises/back/seated-cable-row.webp",
    instructions: [
      "שבו מול הפולי עם ברכיים מעט כפופות וגב ישר.",
      "משכו את הידית אל הבטן תוך כיווץ השכמות.",
      "החזירו בשליטה עד מתיחה מלאה של הגב.",
    ],
  },
  {
    id: "single-arm-dumbbell-row",
    nameEn: "Single Arm Dumbbell Row",
    nameHe: "חתירת משקולת ביד אחת",
    muscleGroup: "back",
    secondaryMuscles: ["biceps", "core"],
    equipment: "dumbbell",
    difficulty: "beginner",
    imageKey: "single-arm-dumbbell-row",
    imagePath: "/exercises/back/single-arm-dumbbell-row.webp",
    instructions: [
      "הניחו יד וברך על ספסל ושמרו על גב ישר.",
      "משכו את המשקולת אל המותן תוך כיווץ השכמה.",
      "הורידו בשליטה למתיחה מלאה.",
    ],
  },
  {
    id: "face-pull",
    nameEn: "Face Pull",
    nameHe: "פייס פול",
    muscleGroup: "back",
    secondaryMuscles: ["shoulders"],
    equipment: "cable",
    difficulty: "beginner",
    imageKey: "face-pull",
    imagePath: "/exercises/back/face-pull.webp",
    instructions: [
      "כוונו את הפולי לגובה הפנים עם חבל כפול.",
      "משכו את החבל אל הפנים תוך פתיחת המרפקים לצדדים.",
      "החזירו בשליטה תוך שמירה על כתפיים משוחררות.",
    ],
    notes: "תרגיל מצוין לחיזוק הכתף האחורית ויציבה.",
  },
  {
    id: "close-grip-lat-pulldown",
    nameEn: "Close Grip Lat Pulldown",
    nameHe: "פולי עליון באחיזה צרה",
    muscleGroup: "back",
    secondaryMuscles: ["biceps"],
    equipment: "cable",
    difficulty: "beginner",
    imageKey: "close-grip-lat-pulldown",
    imagePath: "/exercises/back/close-grip-lat-pulldown.webp",
    instructions: [
      "אחזו בידית צרה כשכפות הידיים קרובות זו לזו.",
      "משכו את הידית אל בית החזה תוך כיווץ השכמות.",
      "החזירו בשליטה למתיחה מלאה.",
    ],
  },
  {
    id: "chest-supported-row",
    nameEn: "Chest Supported Row",
    nameHe: "חתירה בתמיכת חזה",
    muscleGroup: "back",
    secondaryMuscles: ["biceps"],
    equipment: "machine",
    difficulty: "beginner",
    imageKey: "chest-supported-row",
    imagePath: "/exercises/back/chest-supported-row.webp",
    instructions: [
      "הצמידו את החזה למשענת ואחזו בידיות.",
      "משכו את הידיות לאחור תוך כיווץ השכמות.",
      "החזירו בשליטה למתיחה מלאה.",
    ],
    notes: "התמיכה מנטרלת את הגב התחתון ומבודדת את שרירי הגב.",
  },
  {
    id: "straight-arm-pulldown",
    nameEn: "Straight Arm Pulldown",
    nameHe: "פולי ישר בידיים ישרות",
    muscleGroup: "back",
    secondaryMuscles: ["triceps"],
    equipment: "cable",
    difficulty: "intermediate",
    imageKey: "straight-arm-pulldown",
    imagePath: "/exercises/back/straight-arm-pulldown.webp",
    instructions: [
      "עמדו מול פולי עליון ואחזו במוט בידיים ישרות.",
      "הורידו את המוט אל הירכיים בקשת רחבה ללא כיפוף מרפקים.",
      "החזירו בשליטה למעלה עד מתיחה מלאה של הגב.",
    ],
  },
  {
    id: "single-arm-lat-pulldown",
    nameEn: "Single Arm Lat Pulldown",
    nameHe: "פולי עליון ביד אחת",
    muscleGroup: "back",
    secondaryMuscles: ["biceps"],
    equipment: "cable",
    difficulty: "beginner",
    imageKey: "single-arm-lat-pulldown",
    imagePath: "/exercises/back/single-arm-lat-pulldown.webp",
    instructions: [
      "אחזו בידית פולי עליון ביד אחת.",
      "משכו את הידית אל הכתף תוך כיווץ השכמה.",
      "החזירו בשליטה למתיחה מלאה.",
    ],
  },
  {
    id: "t-bar-row",
    nameEn: "T-Bar Row",
    nameHe: "חתירת טי-בר",
    muscleGroup: "back",
    secondaryMuscles: ["biceps", "core"],
    equipment: "barbell",
    difficulty: "intermediate",
    imageKey: "t-bar-row",
    imagePath: "/exercises/back/t-bar-row.webp",
    instructions: [
      "עמדו מעל המוט בהרכנה עם גב ישר.",
      "משכו את הידית אל בית החזה תוך כיווץ השכמות.",
      "הורידו בשליטה עד מתיחה מלאה.",
    ],
  },
  {
    id: "wide-grip-lat-pulldown",
    nameEn: "Wide Grip Lat Pulldown",
    nameHe: "פולי עליון באחיזה רחבה",
    muscleGroup: "back",
    secondaryMuscles: ["biceps"],
    equipment: "cable",
    difficulty: "beginner",
    imageKey: "wide-grip-lat-pulldown",
    imagePath: "/exercises/back/wide-grip-lat-pulldown.webp",
    instructions: [
      "אחזו במוט באחיזה רחבה משמעותית מרוחב הכתפיים.",
      "משכו את המוט אל בית החזה תוך כיווץ השכמות.",
      "החזירו בשליטה למתיחה מלאה.",
    ],
  },
  {
    id: "reverse-grip-lat-pulldown",
    nameEn: "Reverse Grip Lat Pulldown",
    nameHe: "פולי עליון באחיזה הפוכה",
    muscleGroup: "back",
    secondaryMuscles: ["biceps"],
    equipment: "cable",
    difficulty: "beginner",
    imageKey: "reverse-grip-lat-pulldown",
    imagePath: "/exercises/back/reverse-grip-lat-pulldown.webp",
    instructions: [
      "אחזו במוט באחיזה הפוכה ברוחב הכתפיים.",
      "משכו את המוט אל בית החזה תוך כיווץ השכמות.",
      "החזירו בשליטה למתיחה מלאה.",
    ],
  },
  {
    id: "wide-grip-seated-row",
    nameEn: "Wide Grip Seated Row",
    nameHe: "חתירה בישיבה באחיזה רחבה",
    muscleGroup: "back",
    secondaryMuscles: ["biceps", "shoulders"],
    equipment: "cable",
    difficulty: "beginner",
    imageKey: "wide-grip-seated-row",
    imagePath: "/exercises/back/wide-grip-seated-row.webp",
    instructions: [
      "שבו מול הפולי ואחזו במוט רחב בשתי הידיים.",
      "משכו את המוט אל בית החזה עם מרפקים גבוהים.",
      "החזירו בשליטה למתיחה מלאה.",
    ],
  },
  {
    id: "reverse-grip-barbell-row",
    nameEn: "Reverse Grip Barbell Row",
    nameHe: "חתירת מוט באחיזה הפוכה",
    muscleGroup: "back",
    secondaryMuscles: ["biceps", "core"],
    equipment: "barbell",
    difficulty: "intermediate",
    imageKey: "reverse-grip-barbell-row",
    imagePath: "/exercises/back/reverse-grip-barbell-row.webp",
    instructions: [
      "הרכינו את פלג הגוף העליון עם גב ישר ואחיזה הפוכה.",
      "משכו את המוט אל הבטן התחתונה.",
      "הורידו בשליטה ושמרו על ליבה אקטיבית.",
    ],
  },
  {
    id: "bench-press",
    nameEn: "Bench Press",
    nameHe: "לחיצת חזה",
    muscleGroup: "chest",
    secondaryMuscles: ["triceps", "shoulders"],
    equipment: "barbell",
    difficulty: "intermediate",
    imageKey: "bench-press",
    imagePath: "/exercises/chest/bench-press.webp",
    instructions: [
      "שכבו על הספסל עם אחיזה מעט רחבה מהכתפיים.",
      "הורידו את המוט אל אמצע החזה בשליטה.",
      "דחפו כלפי מעלה עד יישור המרפקים.",
    ],
  },
  {
    id: "incline-bench-press",
    nameEn: "Incline Bench Press",
    nameHe: "לחיצת חזה בשיפוע עולה",
    muscleGroup: "chest",
    secondaryMuscles: ["shoulders", "triceps"],
    equipment: "barbell",
    difficulty: "intermediate",
    imageKey: "incline-bench-press",
    imagePath: "/exercises/chest/incline-bench-press.webp",
    instructions: [
      "שכבו על ספסל בשיפוע של 30-45 מעלות.",
      "הורידו את המוט אל החזה העליון בשליטה.",
      "דחפו כלפי מעלה עד יישור המרפקים.",
    ],
    notes: "השיפוע מעביר דגש לחלק העליון של החזה.",
  },
  {
    id: "decline-bench-press",
    nameEn: "Decline Bench Press",
    nameHe: "לחיצת חזה בשיפוע יורד",
    muscleGroup: "chest",
    secondaryMuscles: ["triceps"],
    equipment: "barbell",
    difficulty: "intermediate",
    imageKey: "decline-bench-press",
    imagePath: "/exercises/chest/decline-bench-press.webp",
    instructions: [
      "שכבו על ספסל בשיפוע יורד עם רגליים מקובעות.",
      "הורידו את המוט אל החזה התחתון בשליטה.",
      "דחפו כלפי מעלה עד יישור המרפקים.",
    ],
  },
  {
    id: "dumbbell-bench-press",
    nameEn: "Dumbbell Bench Press",
    nameHe: "לחיצת חזה עם משקולות",
    muscleGroup: "chest",
    secondaryMuscles: ["triceps", "shoulders"],
    equipment: "dumbbell",
    difficulty: "beginner",
    imageKey: "dumbbell-bench-press",
    imagePath: "/exercises/chest/dumbbell-bench-press.webp",
    instructions: [
      "שכבו על ספסל עם משקולת בכל יד בגובה החזה.",
      "דחפו את המשקולות כלפי מעלה עד יישור המרפקים.",
      "הורידו בשליטה לגובה החזה.",
    ],
    notes: "מאפשר טווח תנועה גדול יותר מלחיצה עם מוט.",
  },
  {
    id: "incline-dumbbell-press",
    nameEn: "Incline Dumbbell Press",
    nameHe: "לחיצת משקולות בשיפוע עולה",
    muscleGroup: "chest",
    secondaryMuscles: ["shoulders", "triceps"],
    equipment: "dumbbell",
    difficulty: "intermediate",
    imageKey: "incline-dumbbell-press",
    imagePath: "/exercises/chest/incline-dumbbell-press.webp",
    instructions: [
      "שכבו על ספסל בשיפוע עולה עם משקולת בכל יד.",
      "דחפו את המשקולות כלפי מעלה מעל החזה העליון.",
      "הורידו בשליטה לגובה הכתפיים.",
    ],
  },
  {
    id: "chest-fly",
    nameEn: "Chest Fly",
    nameHe: "פרפר עם משקולות",
    muscleGroup: "chest",
    secondaryMuscles: ["shoulders"],
    equipment: "dumbbell",
    difficulty: "beginner",
    imageKey: "chest-fly",
    imagePath: "/exercises/chest/chest-fly.webp",
    instructions: [
      "שכבו על ספסל עם משקולות מעל החזה וכפות ידיים פונות זו לזו.",
      "פתחו את הידיים לצדדים בקשת רחבה עם מרפקים מעט כפופים.",
      "החזירו את המשקולות מעלה באותה קשת תוך כיווץ החזה.",
    ],
  },
  {
    id: "incline-dumbbell-fly",
    nameEn: "Incline Dumbbell Fly",
    nameHe: "פרפר בשיפוע עולה",
    muscleGroup: "chest",
    secondaryMuscles: ["shoulders"],
    equipment: "dumbbell",
    difficulty: "intermediate",
    imageKey: "incline-dumbbell-fly",
    imagePath: "/exercises/chest/incline-dumbbell-fly.webp",
    instructions: [
      "שכבו על ספסל בשיפוע עולה עם משקולות מעל החזה.",
      "פתחו את הידיים לצדדים בקשת רחבה עם מרפקים מעט כפופים.",
      "החזירו מעלה תוך כיווץ החזה העליון.",
    ],
  },
  {
    id: "cable-chest-fly",
    nameEn: "Cable Chest Fly",
    nameHe: "פרפר בפולי",
    muscleGroup: "chest",
    secondaryMuscles: ["shoulders"],
    equipment: "cable",
    difficulty: "beginner",
    imageKey: "cable-chest-fly",
    imagePath: "/exercises/chest/cable-chest-fly.webp",
    instructions: [
      "עמדו בין שני פולים בגובה החזה עם ידית בכל יד.",
      "קרבו את הידיים זו לזו לפנים בקשת רחבה.",
      "החזירו בשליטה עד מתיחה נעימה בחזה.",
    ],
    notes: "הפולי שומר על מתח רציף לאורך כל התנועה.",
  },
  {
    id: "low-cable-fly",
    nameEn: "Low Cable Fly",
    nameHe: "פרפר בפולי תחתון",
    muscleGroup: "chest",
    secondaryMuscles: ["shoulders"],
    equipment: "cable",
    difficulty: "intermediate",
    imageKey: "low-cable-fly",
    imagePath: "/exercises/chest/low-cable-fly.webp",
    instructions: [
      "כוונו את הפולים לעמדה נמוכה ואחזו בידיות.",
      "הרימו את הידיים מלמטה כלפי מעלה ופנימה אל מול החזה.",
      "החזירו בשליטה למצב התחלתי.",
    ],
    notes: "דגש על החלק העליון של החזה.",
  },
  {
    id: "high-cable-fly",
    nameEn: "High Cable Fly",
    nameHe: "פרפר בפולי עליון",
    muscleGroup: "chest",
    secondaryMuscles: ["shoulders"],
    equipment: "cable",
    difficulty: "intermediate",
    imageKey: "high-cable-fly",
    imagePath: "/exercises/chest/high-cable-fly.webp",
    instructions: [
      "כוונו את הפולים לעמדה גבוהה ואחזו בידיות.",
      "משכו את הידיים מלמעלה כלפי מטה ופנימה אל מול הבטן.",
      "החזירו בשליטה למצב התחלתי.",
    ],
    notes: "דגש על החלק התחתון של החזה.",
  },
  {
    id: "machine-chest-press",
    nameEn: "Machine Chest Press",
    nameHe: "לחיצת חזה במכונה",
    muscleGroup: "chest",
    secondaryMuscles: ["triceps"],
    equipment: "machine",
    difficulty: "beginner",
    imageKey: "machine-chest-press",
    imagePath: "/exercises/chest/machine-chest-press.webp",
    instructions: [
      "שבו במכונה עם הידיות בגובה החזה.",
      "דחפו את הידיות קדימה עד יישור המרפקים.",
      "החזירו בשליטה למצב התחלתי.",
    ],
    notes: "מסלול מונחה — מתאים מאוד למתחילים.",
  },
  {
    id: "pec-deck-fly",
    nameEn: "Pec Deck Fly",
    nameHe: "פרפר במכונה",
    muscleGroup: "chest",
    secondaryMuscles: ["shoulders"],
    equipment: "machine",
    difficulty: "beginner",
    imageKey: "pec-deck-fly",
    imagePath: "/exercises/chest/pec-deck-fly.webp",
    instructions: [
      "שבו במכונה עם גב צמוד למשענת וידיים על הידיות.",
      "קרבו את הידיות זו לזו תוך כיווץ החזה.",
      "החזירו בשליטה עד מתיחה נעימה.",
    ],
  },
  {
    id: "smith-machine-bench-press",
    nameEn: "Smith Machine Bench Press",
    nameHe: "לחיצת חזה בסמית' משין",
    muscleGroup: "chest",
    secondaryMuscles: ["triceps", "shoulders"],
    equipment: "machine",
    difficulty: "beginner",
    imageKey: "smith-machine-bench-press",
    imagePath: "/exercises/chest/smith-machine-bench-press.webp",
    instructions: [
      "שכבו על ספסל מתחת למוט הסמית' משין.",
      "הורידו את המוט אל אמצע החזה בשליטה.",
      "דחפו כלפי מעלה עד יישור המרפקים.",
    ],
    notes: "המסלול הקבוע מאפשר עבודה בטוחה ללא שומר.",
  },
  {
    id: "push-up",
    nameEn: "Push Up",
    nameHe: "שכיבות סמיכה",
    muscleGroup: "chest",
    secondaryMuscles: ["triceps", "core"],
    equipment: "bodyweight",
    difficulty: "beginner",
    imageKey: "push-up",
    imagePath: "/exercises/chest/push-up.webp",
    instructions: [
      "התמקמו בפלאנק עם ידיים מעט רחבות מהכתפיים.",
      "הורידו את הגוף עד שהחזה כמעט נוגע ברצפה.",
      "דחפו חזרה למעלה תוך שמירה על גוף ישר.",
    ],
  },
  {
    id: "incline-push-up",
    nameEn: "Incline Push Up",
    nameHe: "שכיבות סמיכה בשיפוע עולה",
    muscleGroup: "chest",
    secondaryMuscles: ["triceps", "core"],
    equipment: "bodyweight",
    difficulty: "beginner",
    imageKey: "incline-push-up",
    imagePath: "/exercises/chest/incline-push-up.webp",
    instructions: [
      "הניחו את הידיים על משטח מוגבה כמו ספסל.",
      "הורידו את החזה אל המשטח בשליטה.",
      "דחפו חזרה למעלה תוך שמירה על גוף ישר.",
    ],
    notes: "גרסה קלה יותר — מתאימה לבניית בסיס.",
  },
  {
    id: "decline-push-up",
    nameEn: "Decline Push Up",
    nameHe: "שכיבות סמיכה בשיפוע יורד",
    muscleGroup: "chest",
    secondaryMuscles: ["shoulders", "triceps"],
    equipment: "bodyweight",
    difficulty: "intermediate",
    imageKey: "decline-push-up",
    imagePath: "/exercises/chest/decline-push-up.webp",
    instructions: [
      "הניחו את כפות הרגליים על משטח מוגבה וידיים על הרצפה.",
      "הורידו את החזה אל הרצפה בשליטה.",
      "דחפו חזרה למעלה תוך שמירה על גוף ישר.",
    ],
    notes: "ההגבהה מעבירה דגש לחזה העליון ולכתפיים.",
  },
  {
    id: "dips-chest-focus",
    nameEn: "Dips (Chest Focus)",
    nameHe: "מקבילים בדגש חזה",
    muscleGroup: "chest",
    secondaryMuscles: ["triceps", "shoulders"],
    equipment: "bodyweight",
    difficulty: "advanced",
    imageKey: "dips-chest-focus",
    imagePath: "/exercises/chest/dips-chest-focus.webp",
    instructions: [
      "אחזו במקבילים והרכינו את פלג הגוף העליון מעט קדימה.",
      "רדו בשליטה עד שהכתפיים בגובה המרפקים.",
      "דחפו חזרה למעלה תוך שמירה על ההרכנה קדימה.",
    ],
    notes: "ההרכנה קדימה מעבירה את הדגש מהיד האחורית לחזה.",
  },
  {
    id: "dumbbell-pullover",
    nameEn: "Dumbbell Pullover",
    nameHe: "פולאובר עם משקולת",
    muscleGroup: "chest",
    secondaryMuscles: ["back", "triceps"],
    equipment: "dumbbell",
    difficulty: "intermediate",
    imageKey: "dumbbell-pullover",
    imagePath: "/exercises/chest/dumbbell-pullover.webp",
    instructions: [
      "שכבו על ספסל ואחזו משקולת אחת בשתי הידיים מעל החזה.",
      "הורידו את המשקולת לאחור מעבר לראש בקשת רחבה.",
      "החזירו מעל החזה תוך כיווץ החזה והגב.",
    ],
  },
  {
    id: "landmine-chest-press",
    nameEn: "Landmine Chest Press",
    nameHe: "לחיצת חזה בלנדמיין",
    muscleGroup: "chest",
    secondaryMuscles: ["shoulders", "triceps"],
    equipment: "barbell",
    difficulty: "intermediate",
    imageKey: "landmine-chest-press",
    imagePath: "/exercises/chest/landmine-chest-press.webp",
    instructions: [
      "הציבו את קצה המוט בעוגן לנדמיין ואחזו בקצה הפנוי בגובה החזה.",
      "דחפו את המוט קדימה ומעלה עד יישור הזרוע.",
      "החזירו בשליטה לגובה החזה.",
    ],
  },
  {
    id: "svend-press",
    nameEn: "Svend Press",
    nameHe: "לחיצת סבנד",
    muscleGroup: "chest",
    secondaryMuscles: ["shoulders", "triceps"],
    equipment: "dumbbell",
    difficulty: "beginner",
    imageKey: "svend-press",
    imagePath: "/exercises/chest/svend-press.webp",
    instructions: [
      "לחצו משקל קל בין שתי כפות הידיים בגובה החזה.",
      "דחפו את המשקל קדימה תוך לחיצה מתמשכת של הידיים זו אל זו.",
      "החזירו בשליטה אל החזה.",
    ],
    notes: "מתבצע לרוב עם צלחת משקל; הציוד מסומן כמשקולת לבדיקה עתידית.",
  },
  {
    id: "shoulder-press",
    nameEn: "Shoulder Press",
    nameHe: "לחיצת כתפיים",
    muscleGroup: "shoulders",
    secondaryMuscles: ["triceps"],
    equipment: "dumbbell",
    difficulty: "beginner",
    imageKey: "shoulder-press",
    imagePath: "/exercises/shoulders/shoulder-press.webp",
    instructions: [
      "אחזו משקולות בגובה הכתפיים.",
      "דחפו כלפי מעלה עד יישור הזרועות.",
      "הורידו בשליטה לגובה הכתפיים.",
    ],
    notes: "התמונה ממחישה לחיצה בישיבה עם משקולות.",
  },
  {
    id: "squat",
    nameEn: "Squat",
    nameHe: "סקוואט",
    muscleGroup: "legs",
    secondaryMuscles: ["glutes", "core"],
    equipment: "barbell",
    difficulty: "intermediate",
    imageKey: "squat",
    imagePath: "/exercises/legs/squat.webp",
    instructions: [
      "הניחו את המוט על הטרפזים העליונים.",
      "רדו תוך דחיפת ירכיים אחורה עד עומק מקביל.",
      "דחפו דרך העקבים בחזרה למעלה.",
    ],
    notes: "שמרו על ברכיים בכיוון האצבעות.",
  },
  {
    id: "biceps-curl",
    nameEn: "Biceps Curl",
    nameHe: "כפיפת מרפקים",
    muscleGroup: "biceps",
    secondaryMuscles: [],
    equipment: "dumbbell",
    difficulty: "beginner",
    imageKey: "biceps-curl",
    imagePath: "/exercises/biceps/biceps-curl.webp",
    instructions: [
      "עמדו עם משקולות לצד הגוף.",
      "כפפו את המרפקים והרימו את המשקולות.",
      "הורידו בשליטה מלאה.",
    ],
  },
  {
    id: "triceps-pushdown",
    nameEn: "Triceps Pushdown",
    nameHe: "פשיטת מרפקים בפולי",
    muscleGroup: "triceps",
    secondaryMuscles: [],
    equipment: "cable",
    difficulty: "beginner",
    imageKey: "triceps-pushdown",
    instructions: [
      "אחזו בידית הפולי בגובה החזה.",
      "פשטו את המרפקים כלפי מטה עד יישור מלא.",
      "החזירו בשליטה תוך שמירה על מרפקים צמודים.",
    ],
  },
  {
    id: "plank",
    nameEn: "Plank",
    nameHe: "פלאנק",
    muscleGroup: "core",
    secondaryMuscles: ["shoulders"],
    equipment: "bodyweight",
    difficulty: "beginner",
    imageKey: "plank",
    instructions: [
      "התמקמו על האמות וקצות האצבעות.",
      "שמרו על קו ישר מהראש ועד העקבים.",
      "כווצו ליבה ועכוז והחזיקו את הזמן הנדרש.",
    ],
  },
  // --- Legs (Phase 3.6) ---
  {
    id: "bulgarian-split-squat",
    nameEn: "Bulgarian Split Squat",
    nameHe: "סקוואט בולגרי",
    muscleGroup: "legs",
    secondaryMuscles: ["glutes", "core"],
    equipment: "dumbbell",
    difficulty: "intermediate",
    imageKey: "bulgarian-split-squat",
    imagePath: "/exercises/legs/bulgarian-split-squat.webp",
    instructions: [
      "הניחו את כף הרגל האחורית על ספסל מאחוריכם.",
      "רדו עם הרגל הקדמית עד שהירך מקבילה לרצפה.",
      "דחפו דרך העקב הקדמי בחזרה למעלה.",
    ],
    notes: "שמרו על יציבות ושיווי משקל לאורך התנועה.",
  },
  {
    id: "dumbbell-goblet-squat",
    nameEn: "Dumbbell Goblet Squat",
    nameHe: "סקוואט גביע עם משקולת",
    muscleGroup: "legs",
    secondaryMuscles: ["glutes", "core"],
    equipment: "dumbbell",
    difficulty: "beginner",
    imageKey: "dumbbell-goblet-squat",
    imagePath: "/exercises/legs/dumbbell-goblet-squat.webp",
    instructions: [
      "אחזו משקולת אחת אנכית מול בית החזה.",
      "רדו לסקוואט תוך שמירה על גב ישר וחזה פתוח.",
      "דחפו דרך העקבים בחזרה למעלה.",
    ],
    notes: "מצוין ללימוד טכניקת סקוואט נכונה.",
  },
  {
    id: "hack-squat",
    nameEn: "Hack Squat",
    nameHe: "האק סקוואט",
    muscleGroup: "legs",
    secondaryMuscles: ["glutes"],
    equipment: "machine",
    difficulty: "intermediate",
    imageKey: "hack-squat",
    imagePath: "/exercises/legs/hack-squat.webp",
    instructions: [
      "התמקמו במכונה עם הגב צמוד למשענת.",
      "רדו תוך כיפוף הברכיים עד עומק מקביל.",
      "דחפו דרך העקבים בחזרה למעלה.",
    ],
  },
  {
    id: "leg-curl-machine",
    nameEn: "Leg Curl Machine",
    nameHe: "כפיפת ברך במכונה (שכיבה)",
    muscleGroup: "legs",
    secondaryMuscles: [],
    equipment: "machine",
    difficulty: "beginner",
    imageKey: "leg-curl-machine",
    imagePath: "/exercises/legs/leg-curl-machine.webp",
    instructions: [
      "שכבו על המכונה עם הכרית מעל גידי הברך.",
      "כפפו את הברכיים ומשכו את העקבים אל הישבן.",
      "הורידו בשליטה למצב התחלתי.",
    ],
    notes: "ממוקד בשרירי הירך האחורית.",
  },
  {
    id: "leg-extension",
    nameEn: "Leg Extension",
    nameHe: "פשיטת ברך במכונה",
    muscleGroup: "legs",
    secondaryMuscles: [],
    equipment: "machine",
    difficulty: "beginner",
    imageKey: "leg-extension",
    imagePath: "/exercises/legs/leg-extension.webp",
    instructions: [
      "שבו במכונה עם הכרית מעל קרסולי הרגליים.",
      "פשטו את הברכיים עד יישור מלא תוך כיווץ הירך הקדמית.",
      "הורידו בשליטה למצב התחלתי.",
    ],
    notes: "ממוקד בשרירי הירך הקדמית.",
  },
  {
    id: "leg-press",
    nameEn: "Leg Press",
    nameHe: "לחיצת רגליים",
    muscleGroup: "legs",
    secondaryMuscles: ["glutes"],
    equipment: "machine",
    difficulty: "beginner",
    imageKey: "leg-press",
    imagePath: "/exercises/legs/leg-press.webp",
    instructions: [
      "הניחו את כפות הרגליים על המשטח ברוחב הכתפיים.",
      "כפפו את הברכיים והורידו את המשטח בשליטה.",
      "דחפו דרך העקבים עד יישור כמעט מלא של הברכיים.",
    ],
    notes: "אל תנעלו את הברכיים בחלק העליון של התנועה.",
  },
  {
    id: "reverse-lunges",
    nameEn: "Reverse Lunges",
    nameHe: "מספריים לאחור",
    muscleGroup: "legs",
    secondaryMuscles: ["glutes", "core"],
    equipment: "dumbbell",
    difficulty: "beginner",
    imageKey: "reverse-lunges",
    imagePath: "/exercises/legs/reverse-lunges.webp",
    instructions: [
      "אחזו משקולות לצד הגוף ועמדו זקופים.",
      "פסעו אחורה ורדו עד שהברך האחורית כמעט נוגעת ברצפה.",
      "דחפו דרך הרגל הקדמית בחזרה לעמידה.",
    ],
  },
  {
    id: "seated-calf-raise",
    nameEn: "Seated Calf Raise",
    nameHe: "כפיפת שוקיים בישיבה",
    muscleGroup: "legs",
    secondaryMuscles: [],
    equipment: "machine",
    difficulty: "beginner",
    imageKey: "seated-calf-raise",
    imagePath: "/exercises/legs/seated-calf-raise.webp",
    instructions: [
      "שבו עם כריות המשקל על הירכיים וקדמת כף הרגל על המדרך.",
      "הרימו את העקבים גבוה ככל האפשר תוך כיווץ השוקיים.",
      "הורידו בשליטה עד מתיחה מלאה.",
    ],
  },
  {
    id: "seated-leg-curl",
    nameEn: "Seated Leg Curl",
    nameHe: "כפיפת ברך בישיבה",
    muscleGroup: "legs",
    secondaryMuscles: [],
    equipment: "machine",
    difficulty: "beginner",
    imageKey: "seated-leg-curl",
    imagePath: "/exercises/legs/seated-leg-curl.webp",
    instructions: [
      "שבו במכונה עם הכרית מעל גב הקרסוליים.",
      "כפפו את הברכיים ומשכו את הכרית כלפי מטה.",
      "החזירו בשליטה למצב התחלתי.",
    ],
    notes: "ממוקד בשרירי הירך האחורית.",
  },
  {
    id: "smith-machine-squat",
    nameEn: "Smith Machine Squat",
    nameHe: "סקוואט בסמית' משין",
    muscleGroup: "legs",
    secondaryMuscles: ["glutes", "core"],
    equipment: "machine",
    difficulty: "beginner",
    imageKey: "smith-machine-squat",
    imagePath: "/exercises/legs/smith-machine-squat.webp",
    instructions: [
      "התמקמו מתחת למוט הסמית' משין על הטרפזים העליונים.",
      "רדו לסקוואט עד עומק מקביל בשליטה.",
      "דחפו דרך העקבים בחזרה למעלה.",
    ],
    notes: "המסלול הקבוע מאפשר עבודה בטוחה ויציבה.",
  },
  {
    id: "standing-calf-raise",
    nameEn: "Standing Calf Raise",
    nameHe: "כפיפת שוקיים בעמידה",
    muscleGroup: "legs",
    secondaryMuscles: [],
    equipment: "machine",
    difficulty: "beginner",
    imageKey: "standing-calf-raise",
    imagePath: "/exercises/legs/standing-calf-raise.webp",
    instructions: [
      "עמדו עם קדמת כף הרגל על המדרך והכתפיים תחת הכריות.",
      "הרימו את העקבים גבוה ככל האפשר תוך כיווץ השוקיים.",
      "הורידו בשליטה עד מתיחה מלאה.",
    ],
  },
  {
    id: "step-up",
    nameEn: "Step Up",
    nameHe: "עליית מדרגה",
    muscleGroup: "legs",
    secondaryMuscles: ["glutes", "core"],
    equipment: "dumbbell",
    difficulty: "beginner",
    imageKey: "step-up",
    imagePath: "/exercises/legs/step-up.webp",
    instructions: [
      "אחזו משקולות לצד הגוף ועמדו מול ספסל יציב.",
      "עלו עם רגל אחת ודחפו דרך העקב עד עמידה מלאה.",
      "רדו בשליטה והחליפו רגליים.",
    ],
  },
  {
    id: "sumo-squat",
    nameEn: "Sumo Squat",
    nameHe: "סקוואט סומו",
    muscleGroup: "legs",
    secondaryMuscles: ["glutes"],
    equipment: "dumbbell",
    difficulty: "beginner",
    imageKey: "sumo-squat",
    imagePath: "/exercises/legs/sumo-squat.webp",
    instructions: [
      "עמדו ברגליים רחבות וכפות רגליים מופנות החוצה.",
      "אחזו משקולת מול הגוף ורדו לסקוואט עמוק.",
      "דחפו דרך העקבים בחזרה למעלה תוך כיווץ העכוז.",
    ],
    notes: "העמדה הרחבה מערבת יותר את העכוז ופנים הירך.",
  },
  {
    id: "walking-lunges",
    nameEn: "Walking Lunges",
    nameHe: "מספריים בהליכה",
    muscleGroup: "legs",
    secondaryMuscles: ["glutes", "core"],
    equipment: "dumbbell",
    difficulty: "intermediate",
    imageKey: "walking-lunges",
    imagePath: "/exercises/legs/walking-lunges.webp",
    instructions: [
      "אחזו משקולות לצד הגוף ופסעו קדימה למספריים.",
      "רדו עד שהברך האחורית כמעט נוגעת ברצפה.",
      "דחפו קדימה והמשיכו לפסיעה הבאה לסירוגין.",
    ],
  },
  {
    id: "wall-sit",
    nameEn: "Wall Sit",
    nameHe: "ישיבת קיר",
    muscleGroup: "legs",
    secondaryMuscles: ["glutes"],
    equipment: "bodyweight",
    difficulty: "beginner",
    imageKey: "wall-sit",
    imagePath: "/exercises/legs/wall-sit.webp",
    instructions: [
      "הישענו עם הגב לקיר והחליקו עד שהירכיים מקבילות לרצפה.",
      "שמרו על ברכיים בזווית 90 מעלות מעל הקרסוליים.",
      "החזיקו את התנוחה למשך הזמן הנדרש.",
    ],
    notes: "תרגיל איזומטרי לסיבולת שרירי הרגליים.",
  },
  // --- Glutes (Phase 3.6) ---
  {
    id: "cable-kickback",
    nameEn: "Cable Kickback",
    nameHe: "בעיטת עכוז בפולי",
    muscleGroup: "glutes",
    secondaryMuscles: ["legs"],
    equipment: "cable",
    difficulty: "beginner",
    imageKey: "cable-kickback",
    imagePath: "/exercises/glutes/cable-kickback.webp",
    instructions: [
      "חברו רצועת קרסול לפולי תחתון ועמדו פונים אל המכונה.",
      "בעטו ברגל אחורה ומעלה תוך כיווץ העכוז.",
      "החזירו בשליטה למצב התחלתי.",
    ],
    notes: "תרגיל בידוד לעכוז.",
  },
  {
    id: "glute-bridge",
    nameEn: "Glute Bridge",
    nameHe: "גשר עכוז",
    muscleGroup: "glutes",
    secondaryMuscles: ["legs"],
    equipment: "bodyweight",
    difficulty: "beginner",
    imageKey: "glute-bridge",
    imagePath: "/exercises/glutes/glute-bridge.webp",
    instructions: [
      "שכבו על הגב עם ברכיים כפופות וכפות רגליים על הרצפה.",
      "הרימו את האגן כלפי מעלה תוך כיווץ העכוז.",
      "הורידו בשליטה מבלי לגעת ברצפה.",
    ],
  },
  {
    id: "hip-thrust",
    nameEn: "Hip Thrust",
    nameHe: "הרמת אגן (היפ תראסט)",
    muscleGroup: "glutes",
    secondaryMuscles: ["legs"],
    equipment: "barbell",
    difficulty: "intermediate",
    imageKey: "hip-thrust",
    imagePath: "/exercises/glutes/hip-thrust.webp",
    instructions: [
      "הישענו עם החלק העליון של הגב על ספסל והניחו מוט על הירכיים.",
      "דחפו דרך העקבים והרימו את האגן עד קו ישר מהברכיים לכתפיים.",
      "הורידו בשליטה למצב התחלתי.",
    ],
    notes: "תרגיל מרכזי לפיתוח שרירי העכוז.",
  },
  // --- Shoulders (Phase 3.6) ---
  {
    id: "arnold-press",
    nameEn: "Arnold Press",
    nameHe: "לחיצת ארנולד",
    muscleGroup: "shoulders",
    secondaryMuscles: ["triceps"],
    equipment: "dumbbell",
    difficulty: "intermediate",
    imageKey: "arnold-press",
    imagePath: "/exercises/shoulders/arnold-press.webp",
    instructions: [
      "התחילו עם משקולות מול הכתפיים וכפות ידיים פונות אליכם.",
      "סובבו את כפות הידיים החוצה תוך דחיפת המשקולות מעלה.",
      "החזירו בשליטה לסיבוב ולמצב ההתחלתי.",
    ],
    notes: "הסיבוב מערב את ראשי הכתף בטווח מלא.",
  },
  {
    id: "barbell-overhead-press",
    nameEn: "Barbell Overhead Press",
    nameHe: "לחיצת כתפיים עם מוט",
    muscleGroup: "shoulders",
    secondaryMuscles: ["triceps", "core"],
    equipment: "barbell",
    difficulty: "intermediate",
    imageKey: "barbell-overhead-press",
    imagePath: "/exercises/shoulders/barbell-overhead-press.webp",
    instructions: [
      "אחזו במוט בגובה הכתפיים ברוחב מעט גדול מהכתפיים.",
      "דחפו את המוט כלפי מעלה עד יישור הזרועות.",
      "הורידו בשליטה לגובה הכתפיים.",
    ],
    notes: "שמרו על ליבה אקטיבית והימנעו מקשת בגב התחתון.",
  },
  {
    id: "barbell-shrug",
    nameEn: "Barbell Shrug",
    nameHe: "משיכת כתפיים עם מוט",
    muscleGroup: "shoulders",
    secondaryMuscles: [],
    equipment: "barbell",
    difficulty: "beginner",
    imageKey: "barbell-shrug",
    imagePath: "/exercises/shoulders/barbell-shrug.webp",
    instructions: [
      "אחזו במוט מול הגוף בידיים ישרות.",
      "הרימו את הכתפיים כלפי מעלה תוך כיווץ הטרפזים.",
      "הורידו בשליטה למצב התחלתי.",
    ],
    notes: "ממוקד בשרירי הטרפז העליון.",
  },
  {
    id: "bent-over-lateral-raise",
    nameEn: "Bent Over Lateral Raise",
    nameHe: "הרחקת ידיים בהרכנה",
    muscleGroup: "shoulders",
    secondaryMuscles: ["back"],
    equipment: "dumbbell",
    difficulty: "beginner",
    imageKey: "bent-over-lateral-raise",
    imagePath: "/exercises/shoulders/bent-over-lateral-raise.webp",
    instructions: [
      "הרכינו את פלג הגוף העליון קדימה עם גב ישר.",
      "הרימו את המשקולות לצדדים תוך כיווץ הכתף האחורית.",
      "הורידו בשליטה למצב התחלתי.",
    ],
    notes: "ממוקד בכתף האחורית.",
  },
  {
    id: "cable-lateral-raise",
    nameEn: "Cable Lateral Raise",
    nameHe: "הרחקת יד בפולי",
    muscleGroup: "shoulders",
    secondaryMuscles: [],
    equipment: "cable",
    difficulty: "beginner",
    imageKey: "cable-lateral-raise",
    imagePath: "/exercises/shoulders/cable-lateral-raise.webp",
    instructions: [
      "עמדו לצד פולי תחתון ואחזו בידית ביד הרחוקה.",
      "הרימו את היד לצד עד גובה הכתף.",
      "הורידו בשליטה למצב התחלתי.",
    ],
    notes: "הפולי שומר על מתח רציף לאורך התנועה.",
  },
  {
    id: "cable-rear-delt-fly",
    nameEn: "Cable Rear Delt Fly",
    nameHe: "פתיחת כתף אחורית בפולי",
    muscleGroup: "shoulders",
    secondaryMuscles: ["back"],
    equipment: "cable",
    difficulty: "intermediate",
    imageKey: "cable-rear-delt-fly",
    imagePath: "/exercises/shoulders/cable-rear-delt-fly.webp",
    instructions: [
      "עמדו בין שני פולים גבוהים ואחזו בידיות במצולב.",
      "משכו את הידיות לאחור ולצדדים תוך כיווץ הכתף האחורית.",
      "החזירו בשליטה למצב התחלתי.",
    ],
    notes: "ממוקד בכתף האחורית.",
  },
  {
    id: "dumbbell-lateral-raise",
    nameEn: "Dumbbell Lateral Raise",
    nameHe: "הרחקת ידיים עם משקולות",
    muscleGroup: "shoulders",
    secondaryMuscles: [],
    equipment: "dumbbell",
    difficulty: "beginner",
    imageKey: "dumbbell-lateral-raise",
    imagePath: "/exercises/shoulders/dumbbell-lateral-raise.webp",
    instructions: [
      "עמדו עם משקולות לצד הגוף וכפות ידיים פונות פנימה.",
      "הרימו את המשקולות לצדדים עד גובה הכתפיים.",
      "הורידו בשליטה למצב התחלתי.",
    ],
    notes: "ממוקד בכתף האמצעית.",
  },
  {
    id: "dumbbell-shrug",
    nameEn: "Dumbbell Shrug",
    nameHe: "משיכת כתפיים עם משקולות",
    muscleGroup: "shoulders",
    secondaryMuscles: [],
    equipment: "dumbbell",
    difficulty: "beginner",
    imageKey: "dumbbell-shrug",
    imagePath: "/exercises/shoulders/dumbbell-shrug.webp",
    instructions: [
      "אחזו משקולות לצד הגוף בידיים ישרות.",
      "הרימו את הכתפיים כלפי מעלה תוך כיווץ הטרפזים.",
      "הורידו בשליטה למצב התחלתי.",
    ],
    notes: "ממוקד בשרירי הטרפז העליון.",
  },
  {
    id: "front-raise",
    nameEn: "Front Raise",
    nameHe: "הרמת יד קדמית",
    muscleGroup: "shoulders",
    secondaryMuscles: [],
    equipment: "dumbbell",
    difficulty: "beginner",
    imageKey: "front-raise",
    imagePath: "/exercises/shoulders/front-raise.webp",
    instructions: [
      "עמדו עם משקולות מול הירכיים.",
      "הרימו משקולת אחת קדימה עד גובה הכתף בזרוע ישרה.",
      "הורידו בשליטה וחזרו לסירוגין.",
    ],
    notes: "ממוקד בכתף הקדמית.",
  },
  {
    id: "landmine-shoulder-press",
    nameEn: "Landmine Shoulder Press",
    nameHe: "לחיצת כתפיים בלנדמיין",
    muscleGroup: "shoulders",
    secondaryMuscles: ["triceps", "core"],
    equipment: "barbell",
    difficulty: "intermediate",
    imageKey: "landmine-shoulder-press",
    imagePath: "/exercises/shoulders/landmine-shoulder-press.webp",
    instructions: [
      "הציבו את קצה המוט בעוגן לנדמיין ואחזו בקצה הפנוי בגובה הכתף.",
      "דחפו את המוט קדימה ומעלה עד יישור הזרוע.",
      "החזירו בשליטה לגובה הכתף.",
    ],
  },
  {
    id: "machine-lateral-raise",
    nameEn: "Machine Lateral Raise",
    nameHe: "הרחקת ידיים במכונה",
    muscleGroup: "shoulders",
    secondaryMuscles: [],
    equipment: "machine",
    difficulty: "beginner",
    imageKey: "machine-lateral-raise",
    imagePath: "/exercises/shoulders/machine-lateral-raise.webp",
    instructions: [
      "שבו במכונה עם הזרועות צמודות לכריות.",
      "הרימו את הכריות לצדדים עד גובה הכתפיים.",
      "הורידו בשליטה למצב התחלתי.",
    ],
    notes: "המסלול המונחה מבודד את הכתף האמצעית.",
  },
  {
    id: "machine-shoulder-press",
    nameEn: "Machine Shoulder Press",
    nameHe: "לחיצת כתפיים במכונה",
    muscleGroup: "shoulders",
    secondaryMuscles: ["triceps"],
    equipment: "machine",
    difficulty: "beginner",
    imageKey: "machine-shoulder-press",
    imagePath: "/exercises/shoulders/machine-shoulder-press.webp",
    instructions: [
      "שבו במכונה עם הידיות בגובה הכתפיים.",
      "דחפו את הידיות כלפי מעלה עד יישור הזרועות.",
      "הורידו בשליטה לגובה הכתפיים.",
    ],
    notes: "מסלול מונחה — מתאים מאוד למתחילים.",
  },
  {
    id: "pike-push-up",
    nameEn: "Pike Push Up",
    nameHe: "שכיבות סמיכה פייק",
    muscleGroup: "shoulders",
    secondaryMuscles: ["triceps", "core"],
    equipment: "bodyweight",
    difficulty: "intermediate",
    imageKey: "pike-push-up",
    imagePath: "/exercises/shoulders/pike-push-up.webp",
    instructions: [
      "התמקמו בתנוחת V הפוכה עם אגן גבוה וידיים על הרצפה.",
      "הורידו את הראש אל הרצפה תוך כיפוף המרפקים.",
      "דחפו חזרה למעלה עד יישור הזרועות.",
    ],
    notes: "גרסת משקל גוף ללחיצת כתפיים.",
  },
  {
    id: "plate-front-raise",
    nameEn: "Plate Front Raise",
    nameHe: "הרמת צלחת קדמית",
    muscleGroup: "shoulders",
    secondaryMuscles: ["core"],
    equipment: "dumbbell",
    difficulty: "beginner",
    imageKey: "plate-front-raise",
    imagePath: "/exercises/shoulders/plate-front-raise.webp",
    instructions: [
      "אחזו צלחת משקל בשתי הידיים מול הירכיים.",
      "הרימו את הצלחת קדימה עד גובה הכתפיים בזרועות ישרות.",
      "הורידו בשליטה למצב התחלתי.",
    ],
    notes: "מתבצע עם צלחת משקל; הציוד מסומן כמשקולת לבדיקה עתידית.",
  },
  {
    id: "rear-delt-fly",
    nameEn: "Rear Delt Fly",
    nameHe: "פתיחת כתף אחורית",
    muscleGroup: "shoulders",
    secondaryMuscles: ["back"],
    equipment: "dumbbell",
    difficulty: "beginner",
    imageKey: "rear-delt-fly",
    imagePath: "/exercises/shoulders/rear-delt-fly.webp",
    instructions: [
      "הרכינו את פלג הגוף העליון קדימה עם גב ישר ומשקולות תלויות.",
      "פתחו את הידיים לצדדים תוך כיווץ הכתף האחורית.",
      "הורידו בשליטה למצב התחלתי.",
    ],
    notes: "ממוקד בכתף האחורית.",
  },
  {
    id: "reverse-pec-deck-fly",
    nameEn: "Reverse Pec Deck Fly",
    nameHe: "פרפר הפוך במכונה",
    muscleGroup: "shoulders",
    secondaryMuscles: ["back"],
    equipment: "machine",
    difficulty: "beginner",
    imageKey: "reverse-pec-deck-fly",
    imagePath: "/exercises/shoulders/reverse-pec-deck-fly.webp",
    instructions: [
      "שבו במכונה עם החזה צמוד למשענת ואחזו בידיות.",
      "פתחו את הידיים לאחור תוך כיווץ הכתף האחורית.",
      "החזירו בשליטה למצב התחלתי.",
    ],
    notes: "ממוקד בכתף האחורית.",
  },
  {
    id: "smith-machine-shoulder-press",
    nameEn: "Smith Machine Shoulder Press",
    nameHe: "לחיצת כתפיים בסמית' משין",
    muscleGroup: "shoulders",
    secondaryMuscles: ["triceps"],
    equipment: "machine",
    difficulty: "beginner",
    imageKey: "smith-machine-shoulder-press",
    imagePath: "/exercises/shoulders/smith-machine-shoulder-press.webp",
    instructions: [
      "שבו תחת מוט הסמית' משין עם המוט בגובה הכתפיים.",
      "דחפו את המוט כלפי מעלה עד יישור הזרועות.",
      "הורידו בשליטה לגובה הכתפיים.",
    ],
    notes: "המסלול הקבוע מאפשר עבודה בטוחה ויציבה.",
  },
  {
    id: "upright-row",
    nameEn: "Upright Row",
    nameHe: "חתירה אנכית",
    muscleGroup: "shoulders",
    secondaryMuscles: ["biceps"],
    equipment: "barbell",
    difficulty: "intermediate",
    imageKey: "upright-row",
    imagePath: "/exercises/shoulders/upright-row.webp",
    instructions: [
      "אחזו במוט מול הגוף באחיזה ברוחב הכתפיים.",
      "משכו את המוט כלפי מעלה לאורך הגוף עד גובה החזה.",
      "הורידו בשליטה למצב התחלתי.",
    ],
    notes: "שמרו על המרפקים גבוהים מהפרקי כף היד.",
  },
  // --- Biceps (Phase 3.8) ---
  {
    id: "barbell-curl",
    nameEn: "Barbell Curl",
    nameHe: "כפיפת מרפקים במוט",
    muscleGroup: "biceps",
    secondaryMuscles: [],
    equipment: "barbell",
    difficulty: "beginner",
    imageKey: "barbell-curl",
    imagePath: "/exercises/biceps/barbell-curl.webp",
    instructions: [
      "עמדו זקופים ואחזו במוט באחיזה תחתית ברוחב הכתפיים.",
      "כפפו את המרפקים והרימו את המוט לכיוון החזה.",
      "הורידו בשליטה מלאה למצב התחלתי.",
    ],
    notes: "שמרו על מרפקים צמודים לגוף ללא תנופה.",
  },
  {
    id: "ez-bar-curl",
    nameEn: "EZ Bar Curl",
    nameHe: "כפיפת מרפקים במוט EZ",
    muscleGroup: "biceps",
    secondaryMuscles: [],
    equipment: "barbell",
    difficulty: "beginner",
    imageKey: "ez-bar-curl",
    imagePath: "/exercises/biceps/ez-bar-curl.webp",
    instructions: [
      "אחזו במוט EZ באחיזה תחתית בזווית הנוחה לפרקי כף היד.",
      "כפפו את המרפקים והרימו את המוט לכיוון החזה.",
      "הורידו בשליטה למצב התחלתי.",
    ],
    notes: "האחיזה הזוויתית מפחיתה עומס על פרקי כף היד.",
  },
  {
    id: "alternating-dumbbell-curl",
    nameEn: "Alternating Dumbbell Curl",
    nameHe: "כפיפת מרפקים לסירוגין",
    muscleGroup: "biceps",
    secondaryMuscles: [],
    equipment: "dumbbell",
    difficulty: "beginner",
    imageKey: "alternating-dumbbell-curl",
    imagePath: "/exercises/biceps/alternating-dumbbell-curl.webp",
    instructions: [
      "עמדו עם משקולת בכל יד לצד הגוף.",
      "כפפו מרפק אחד והרימו את המשקולת, ואז החליפו ידיים.",
      "הורידו כל משקולת בשליטה מלאה.",
    ],
    notes: "שמרו על הגו יציב ללא נדנוד.",
  },
  {
    id: "seated-dumbbell-curl",
    nameEn: "Seated Dumbbell Curl",
    nameHe: "כפיפת מרפקים בישיבה",
    muscleGroup: "biceps",
    secondaryMuscles: [],
    equipment: "dumbbell",
    difficulty: "beginner",
    imageKey: "seated-dumbbell-curl",
    imagePath: "/exercises/biceps/seated-dumbbell-curl.webp",
    instructions: [
      "שבו על ספסל עם משקולת בכל יד לצד הגוף.",
      "כפפו את המרפקים והרימו את המשקולות לכיוון הכתפיים.",
      "הורידו בשליטה למצב התחלתי.",
    ],
    notes: "הישיבה מצמצמת שימוש בתנופה.",
  },
  {
    id: "incline-dumbbell-curl",
    nameEn: "Incline Dumbbell Curl",
    nameHe: "כפיפת מרפקים בשיפוע",
    muscleGroup: "biceps",
    secondaryMuscles: [],
    equipment: "dumbbell",
    difficulty: "intermediate",
    imageKey: "incline-dumbbell-curl",
    imagePath: "/exercises/biceps/incline-dumbbell-curl.webp",
    instructions: [
      "שכבו על ספסל בשיפוע עם משקולת בכל יד לצד הגוף.",
      "כפפו את המרפקים והרימו את המשקולות תוך שמירה על מרפקים אחורה.",
      "הורידו בשליטה למתיחה מלאה.",
    ],
    notes: "השיפוע מגביר את המתיחה על שריר היד הקדמית.",
  },
  {
    id: "concentration-curl",
    nameEn: "Concentration Curl",
    nameHe: "כפיפת ריכוז",
    muscleGroup: "biceps",
    secondaryMuscles: [],
    equipment: "dumbbell",
    difficulty: "beginner",
    imageKey: "concentration-curl",
    imagePath: "/exercises/biceps/concentration-curl.webp",
    instructions: [
      "שבו והניחו את המרפק על פנים הירך.",
      "כפפו את המרפק והרימו את המשקולת לכיוון הכתף.",
      "הורידו בשליטה מלאה.",
    ],
    notes: "תרגיל בידוד טוב לחיבור שריר-מוח.",
  },
  {
    id: "spider-curl",
    nameEn: "Spider Curl",
    nameHe: "כפיפת ספיידר",
    muscleGroup: "biceps",
    secondaryMuscles: [],
    equipment: "dumbbell",
    difficulty: "intermediate",
    imageKey: "spider-curl",
    imagePath: "/exercises/biceps/spider-curl.webp",
    instructions: [
      "שכבו עם החזה על ספסל בשיפוע והניחו את הזרועות תלויות.",
      "כפפו את המרפקים והרימו את המשקולות לכיוון הכתפיים.",
      "הורידו בשליטה למצב התחלתי.",
    ],
    notes: "השכיבה מבטלת תנופה ומבודדת את היד הקדמית.",
  },
  {
    id: "hammer-curl",
    nameEn: "Hammer Curl",
    nameHe: "כפיפת פטיש",
    muscleGroup: "biceps",
    secondaryMuscles: [],
    equipment: "dumbbell",
    difficulty: "beginner",
    imageKey: "hammer-curl",
    imagePath: "/exercises/biceps/hammer-curl.webp",
    instructions: [
      "עמדו עם משקולת בכל יד באחיזה ניטרלית (כפות ידיים פונות פנימה).",
      "כפפו את המרפקים והרימו את המשקולות תוך שמירה על האחיזה.",
      "הורידו בשליטה למצב התחלתי.",
    ],
    notes: "מדגיש את השריר הברכיוני ואת אמת היד.",
  },
  {
    id: "cross-body-hammer-curl",
    nameEn: "Cross Body Hammer Curl",
    nameHe: "כפיפת פטיש חוצה גוף",
    muscleGroup: "biceps",
    secondaryMuscles: [],
    equipment: "dumbbell",
    difficulty: "beginner",
    imageKey: "cross-body-hammer-curl",
    imagePath: "/exercises/biceps/cross-body-hammer-curl.webp",
    instructions: [
      "עמדו עם משקולת בכל יד באחיזה ניטרלית.",
      "הרימו את המשקולת באלכסון לכיוון הכתף הנגדית.",
      "הורידו בשליטה והחליפו ידיים.",
    ],
    notes: "שמרו על מרפק יציב לאורך התנועה.",
  },
  {
    id: "zottman-curl",
    nameEn: "Zottman Curl",
    nameHe: "כפיפת זוטמן",
    muscleGroup: "biceps",
    secondaryMuscles: [],
    equipment: "dumbbell",
    difficulty: "intermediate",
    imageKey: "zottman-curl",
    imagePath: "/exercises/biceps/zottman-curl.webp",
    instructions: [
      "כפפו את המרפקים באחיזה תחתית והרימו את המשקולות.",
      "בחלק העליון סובבו את כפות הידיים לאחיזה הפוכה.",
      "הורידו בשליטה באחיזה ההפוכה וסובבו בחזרה למטה.",
    ],
    notes: "משלב עבודת יד קדמית ואמת היד.",
  },
  {
    id: "reverse-curl",
    nameEn: "Reverse Curl",
    nameHe: "כפיפת מרפקים באחיזה הפוכה",
    muscleGroup: "biceps",
    secondaryMuscles: [],
    equipment: "barbell",
    difficulty: "beginner",
    imageKey: "reverse-curl",
    imagePath: "/exercises/biceps/reverse-curl.webp",
    instructions: [
      "אחזו במוט באחיזה עליונה (כפות ידיים כלפי מטה) ברוחב הכתפיים.",
      "כפפו את המרפקים והרימו את המוט לכיוון החזה.",
      "הורידו בשליטה למצב התחלתי.",
    ],
    notes: "מדגיש את אמת היד והשריר הברכיוני.",
  },
  {
    id: "preacher-curl",
    nameEn: "Preacher Curl",
    nameHe: "כפיפת מרפקים בספסל סקוט",
    muscleGroup: "biceps",
    secondaryMuscles: [],
    equipment: "barbell",
    difficulty: "beginner",
    imageKey: "preacher-curl",
    imagePath: "/exercises/biceps/preacher-curl.webp",
    instructions: [
      "הניחו את הזרועות על משענת ספסל הסקוט ואחזו במוט.",
      "כפפו את המרפקים והרימו את המוט לכיוון הכתפיים.",
      "הורידו בשליטה מבלי לנעול את המרפקים בכוח.",
    ],
    notes: "המשענת מבודדת את היד הקדמית ומונעת תנופה.",
  },
  {
    id: "machine-preacher-curl",
    nameEn: "Machine Preacher Curl",
    nameHe: "כפיפת מרפקים במכונת ספסל סקוט",
    muscleGroup: "biceps",
    secondaryMuscles: [],
    equipment: "machine",
    difficulty: "beginner",
    imageKey: "machine-preacher-curl",
    imagePath: "/exercises/biceps/machine-preacher-curl.webp",
    instructions: [
      "התמקמו במכונה עם הזרועות על המשענת ואחזו בידיות.",
      "כפפו את המרפקים והרימו לכיוון הכתפיים.",
      "הורידו בשליטה למצב התחלתי.",
    ],
    notes: "מסלול קבוע ובטוח לבידוד היד הקדמית.",
  },
  {
    id: "cable-curl",
    nameEn: "Cable Curl",
    nameHe: "כפיפת מרפקים בפולי",
    muscleGroup: "biceps",
    secondaryMuscles: [],
    equipment: "cable",
    difficulty: "beginner",
    imageKey: "cable-curl",
    imagePath: "/exercises/biceps/cable-curl.webp",
    instructions: [
      "עמדו מול הפולי התחתון ואחזו בידית באחיזה תחתית.",
      "כפפו את המרפקים והרימו את הידית לכיוון החזה.",
      "הורידו בשליטה תוך שמירה על מתח קבוע.",
    ],
    notes: "הפולי שומר על מתח קבוע לאורך כל התנועה.",
  },
  {
    id: "single-arm-cable-curl",
    nameEn: "Single Arm Cable Curl",
    nameHe: "כפיפת מרפק יד אחת בפולי",
    muscleGroup: "biceps",
    secondaryMuscles: [],
    equipment: "cable",
    difficulty: "beginner",
    imageKey: "single-arm-cable-curl",
    imagePath: "/exercises/biceps/single-arm-cable-curl.webp",
    instructions: [
      "עמדו לצד הפולי התחתון ואחזו בידית ביד אחת.",
      "כפפו את המרפק והרימו את הידית לכיוון הכתף.",
      "הורידו בשליטה והחליפו ידיים.",
    ],
    notes: "מאפשר התמקדות בכל יד בנפרד.",
  },
  {
    id: "high-cable-curl",
    nameEn: "High Cable Curl",
    nameHe: "כפיפת מרפקים בפולי עליון",
    muscleGroup: "biceps",
    secondaryMuscles: [],
    equipment: "cable",
    difficulty: "intermediate",
    imageKey: "high-cable-curl",
    imagePath: "/exercises/biceps/high-cable-curl.webp",
    instructions: [
      "עמדו בין שני פוליים גבוהים ואחזו בידיות בזרועות פרושות.",
      "כפפו את המרפקים והביאו את הידיות לכיוון הראש.",
      "פשטו בשליטה בחזרה למצב התחלתי.",
    ],
    notes: "שמרו על מרפקים גבוהים וקבועים לאורך התנועה.",
  },
  {
    id: "bayesian-cable-curl",
    nameEn: "Bayesian Cable Curl",
    nameHe: "כפיפת מרפקים בייסיאן בפולי",
    muscleGroup: "biceps",
    secondaryMuscles: [],
    equipment: "cable",
    difficulty: "intermediate",
    imageKey: "bayesian-cable-curl",
    imagePath: "/exercises/biceps/bayesian-cable-curl.webp",
    instructions: [
      "עמדו עם הגב לפולי התחתון ואחזו בידית כשהזרוע מתוחה לאחור.",
      "כפפו את המרפק והרימו את הידית לכיוון הכתף.",
      "פשטו בשליטה למתיחה מלאה.",
    ],
    notes: "המיקום מאחורי הגוף מגביר את המתיחה על היד הקדמית.",
  },
  {
    id: "cable-rope-hammer-curl",
    nameEn: "Cable Rope Hammer Curl",
    nameHe: "כפיפת פטיש בפולי עם חבל",
    muscleGroup: "biceps",
    secondaryMuscles: [],
    equipment: "cable",
    difficulty: "beginner",
    imageKey: "cable-rope-hammer-curl",
    imagePath: "/exercises/biceps/cable-rope-hammer-curl.webp",
    instructions: [
      "עמדו מול הפולי התחתון ואחזו בחבל באחיזה ניטרלית.",
      "כפפו את המרפקים והרימו את החבל לכיוון החזה.",
      "הורידו בשליטה תוך שמירה על מתח קבוע.",
    ],
    notes: "האחיזה הניטרלית מדגישה את השריר הברכיוני.",
  },
  {
    id: "chin-up-biceps-focus",
    nameEn: "Chin Up Biceps Focus",
    nameHe: "מתח באחיזה צרה לדגש על יד קדמית",
    muscleGroup: "biceps",
    secondaryMuscles: ["back"],
    equipment: "bodyweight",
    difficulty: "intermediate",
    imageKey: "chin-up-biceps-focus",
    imagePath: "/exercises/biceps/chin-up-biceps-focus.webp",
    instructions: [
      "אחזו במתח באחיזה תחתית צרה (כפות ידיים פונות אליכם).",
      "משכו את הגוף כלפי מעלה עד שהסנטר מעל המוט.",
      "הורידו בשליטה ליישור מלא של המרפקים.",
    ],
    notes: "אחיזה תחתית מדגישה את היד הקדמית לצד שרירי הגב.",
  },
];

export const MUSCLE_GROUP_LABELS: Record<MuscleGroup, string> = {
  back: "גב",
  chest: "חזה",
  shoulders: "כתפיים",
  legs: "רגליים",
  glutes: "עכוז",
  biceps: "יד קדמית",
  triceps: "יד אחורית",
  core: "ליבה",
};

export const EQUIPMENT_LABELS: Record<Exercise["equipment"], string> = {
  barbell: "מוט",
  dumbbell: "משקולות",
  machine: "מכונה",
  cable: "פולי",
  bodyweight: "משקל גוף",
  kettlebell: "קטלבל",
};

export const DIFFICULTY_LABELS: Record<Exercise["difficulty"], string> = {
  beginner: "מתחיל",
  intermediate: "מתקדם",
  advanced: "מומחה",
};

export function getExerciseById(id: string): Exercise | undefined {
  return SEED_EXERCISES.find((exercise) => exercise.id === id);
}

/** Unique primary muscle groups for a list of exercise ids, in order. */
export function muscleGroupsForExercises(exerciseIds: string[]): MuscleGroup[] {
  const groups = new Set<MuscleGroup>();
  for (const id of exerciseIds) {
    const exercise = getExerciseById(id);
    if (exercise) groups.add(exercise.muscleGroup);
  }
  return [...groups];
}
